name: Publish

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  pages: write

jobs:
  # Build job
  build:
    environment:
      name: github-pages
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: yaml
          github-token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      # - name: Auth composer for private packages
      #   run: composer config --global github-oauth.github.com ${{ secrets.PRIVATE_REPO_TOKEN }}
      # TODO: cache this
      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Build
        run: vendor/bin/ssg build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: .build/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
